insert into auser(id, name, login, email, password) values (10001, 'Admin', 'admin', 'admin@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10002, 'Adam', 'adam', 'adam@admin.com', '123456');
insert into auser(id, name, login, email, password) values (1003, 'Bethany', 'bethany', 'bethany@admin.com','123456');
insert into auser(id, name, login, email, password) values (1004, 'Ciara', 'ciara', 'ciara@admin.com', '123456');
insert into auser(id, name, login, email, password) values (1005, 'Esther', 'esther', 'esther@admin.com', '123456');
insert into auser(id, name, login, email, password) values (1006, 'Amanda', 'amanda', 'amanda@admin.com', '123456');
insert into auser(id, name, login, email, password) values (1007, 'Uillan', 'uillan', 'uillan@admin.com', '123456');
insert into auser(id, name, login, email, password) values (1008, 'Raphaela', 'raphaela', 'raphaela@admin.com','123456');
insert into auser(id, name, login, email, password) values (1009, 'Victor', 'victor', 'victor@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10010, 'Jhuly', 'jhuly', 'jhuly@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10011, 'Mary', 'mary', 'mary@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10012, 'Aileen', 'aileen', 'aileen@admin.com','123456');
insert into auser(id, name, login, email, password) values (10013, 'Bailee', 'bailee', 'bailee@admin.com','123456');
insert into auser(id, name, login, email, password) values (10014, 'Sky', 'sky', 'sky@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10015, 'Mathy', 'mathy', 'mathy@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10016, 'Zoe', 'zoe', 'zoe@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10017, 'Paul', 'paul', 'paul@admin.com', '123456');
insert into auser(id, name, login, email, password) values (10018, 'August', 'august', 'august@admin.com','123456');